#!/bin/bash
# QUICK START GUIDE - Restart Docker and Deploy

echo "🚀 GROQ FALLBACK CLASSIFICATION - DEPLOYMENT QUICK START"
echo "==========================================================="
echo ""

echo "STEP 1: Restart Docker"
echo "--------------------"
echo "Run ONE of the following commands:"
echo ""
echo "Option A (Using helper script):"
echo "  bash /Users/prathamsaurabh/Authenticator.ai/restart_docker.sh"
echo ""
echo "Option B (Manual restart):"
echo "  cd /Users/prathamsaurabh/Authenticator.ai"
echo "  docker-compose down"
echo "  docker-compose up --build -d"
echo "  sleep 30"
echo ""

echo "STEP 2: Verify Deployment"
echo "------------------------"
echo "After Docker restarts, run:"
echo ""
echo "  curl http://localhost:8001/api/health"
echo ""
echo "Expected response:"
echo "  {\"status\":\"healthy\",\"model\":\"llama-3.3-70b-versatile\",...}"
echo ""

echo "STEP 3: Verify Code Integration"
echo "-------------------------------"
echo "Run verification script:"
echo ""
echo "  python3 /Users/prathamsaurabh/Authenticator.ai/verify_groq_fallback.py"
echo ""
echo "Expected: All 4 checks PASSING ✅"
echo ""

echo "STEP 4: Test Classification"
echo "----------------------------"
echo "1. Upload a document with ambiguous/mixed content"
echo "2. Check Layer 2 classification response"
echo "3. Look for: fallback_used: true"
echo "4. Verify groq_reasoning and groq_indicators present"
echo ""

echo "STEP 5: Frontend Integration (Next)"
echo "-----------------------------------"
echo "Update frontend to display:"
echo "  - 'Enhanced by Groq AI' badge when fallback_used: true"
echo "  - Show confidence improvement (original_score -> score)"
echo "  - Display groq_reasoning to user"
echo "  - Show groq_indicators"
echo ""

echo "==========================================================="
echo "✅ Everything is ready!"
echo "Just run: bash restart_docker.sh"
echo "==========================================================="
