#!/usr/bin/env python3
"""
Script to create the BERT training notebook
"""

import json

notebook_content = {
    "cells": [
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "# 🚀 BERT Training Notebook for Authentia.ai Document Classification\n",
                "\n",
                "This notebook provides an interactive way to train and evaluate BERT models for document classification.\n",
                "\n",
                "## 📋 What This Notebook Does:\n",
                "1. **Data Loading**: Loads your cleaned CSV data\n",
                "2. **Model Setup**: Initializes BERT classifier\n",
                "3. **Training**: Trains the model with progress tracking\n",
                "4. **Evaluation**: Tests model performance\n",
                "5. **Visualization**: Shows training curves and results\n",
                "\n",
                "## 🎯 Just Run All Cells and Hit Train!"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📦 Install Dependencies\n",
                "Run this cell to install required packages:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "!pip install torch transformers datasets tokenizers pandas numpy scikit-learn matplotlib seaborn tqdm wandb"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🔧 Import Libraries and Setup"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "import torch\n",
                "import pandas as pd\n",
                "import numpy as np\n",
                "import matplotlib.pyplot as plt\n",
                "import seaborn as sns\n",
                "from sklearn.metrics import classification_report, confusion_matrix, accuracy_score\n",
                "from sklearn.preprocessing import LabelEncoder\n",
                "from transformers import AutoTokenizer, AutoModel, AdamW, get_linear_schedule_with_warmup\n",
                "from torch.utils.data import Dataset, DataLoader\n",
                "import logging\n",
                "from tqdm import tqdm\n",
                "import os\n",
                "import json\n",
                "from datetime import datetime\n",
                "\n",
                "# Configure logging\n",
                "logging.basicConfig(level=logging.INFO)\n",
                "logger = logging.getLogger(__name__)\n",
                "\n",
                "# Set random seeds for reproducibility\n",
                "torch.manual_seed(42)\n",
                "np.random.seed(42)\n",
                "\n",
                "print(\"✅ Libraries imported successfully!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📊 Configuration\n",
                "Set your training parameters here:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Training Configuration\n",
                "CONFIG = {\n",
                "    'model_name': 'bert-base-uncased',\n",
                "    'max_length': 512,\n",
                "    'batch_size': 16,\n",
                "    'learning_rate': 2e-5,\n",
                "    'num_epochs': 5,\n",
                "    'warmup_steps': 500,\n",
                "    'weight_decay': 0.01,\n",
                "    'gradient_accumulation_steps': 4,\n",
                "    'max_grad_norm': 1.0,\n",
                "    'output_dir': './bert_output'\n",
                "}\n",
                "\n",
                "# Data paths\n",
                "TRAIN_FILE = '../data/CLEANED/text_train.csv'\n",
                "VAL_FILE = '../data/CLEANED/text_val.csv'\n",
                "TEST_FILE = '../data/CLEANED/text_test.csv'\n",
                "\n",
                "print(\"✅ Configuration set!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🖥️ Device Setup\n",
                "Check what device we're using:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Device setup\n",
                "device = torch.device(\"cuda\" if torch.cuda.is_available() else \"mps\" if torch.backends.mps.is_available() else \"cpu\")\n",
                "print(f\"🖥️  Using device: {device}\")\n",
                "\n",
                "if device.type == 'cuda':\n",
                "    print(f\"🚀 GPU: {torch.cuda.get_device_name(0)}\")\n",
                "    print(f\"💾 GPU Memory: {torch.cuda.get_device_properties(0).total_memory / 1e9:.1f} GB\")\n",
                "elif device.type == 'mps':\n",
                "    print(\"🍎 Using Apple Silicon (MPS)\")\n",
                "else:\n",
                "    print(\"💻 Using CPU\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📥 Data Loading\n",
                "Load your cleaned CSV data:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Load data\n",
                "print(\"📥 Loading data...\")\n",
                "\n",
                "train_df = pd.read_csv(TRAIN_FILE)\n",
                "val_df = pd.read_csv(VAL_FILE)\n",
                "test_df = pd.read_csv(TEST_FILE)\n",
                "\n",
                "print(f\"📊 Train: {len(train_df)} samples\")\n",
                "print(f\"📊 Validation: {len(val_df)} samples\")\n",
                "print(f\"📊 Test: {len(test_df)} samples\")\n",
                "\n",
                "# Show sample data\n",
                "print(\"\\n📋 Sample training data:\")\n",
                "print(train_df[['cleaned_text', 'category', 'source_type']].head())"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🏷️ Label Encoding\n",
                "Prepare labels for training:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Label encoding\n",
                "label_encoder = LabelEncoder()\n",
                "\n",
                "# Fit on all categories\n",
                "all_categories = train_df['category'].tolist() + val_df['category'].tolist() + test_df['category'].tolist()\n",
                "label_encoder.fit(all_categories)\n",
                "\n",
                "# Transform labels\n",
                "train_labels = label_encoder.transform(train_df['category'])\n",
                "val_labels = label_encoder.transform(val_df['category'])\n",
                "test_labels = label_encoder.transform(test_df['category'])\n",
                "\n",
                "print(f\"🏷️  Categories: {label_encoder.classes_}\")\n",
                "print(f\"🏷️  Number of classes: {len(label_encoder.classes_)}\")\n",
                "\n",
                "# Show label distribution\n",
                "print(\"\\n📊 Label distribution in training set:\")\n",
                "for i, category in enumerate(label_encoder.classes_):\n",
                "    count = (train_labels == i).sum()\n",
                "    print(f\"  {category}: {count} samples\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🤖 BERT Model Setup\n",
                "Initialize the BERT classifier:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Initialize tokenizer and model\n",
                "print(\"🤖 Setting up BERT model...\")\n",
                "\n",
                "tokenizer = AutoTokenizer.from_pretrained(CONFIG['model_name'])\n",
                "model = AutoModel.from_pretrained(CONFIG['model_name'])\n",
                "\n",
                "# Add classification head\n",
                "class BERTClassifier(torch.nn.Module):\n",
                "    def __init__(self, model, num_classes):\n",
                "        super().__init__()\n",
                "        self.bert = model\n",
                "        self.dropout = torch.nn.Dropout(0.1)\n",
                "        self.classifier = torch.nn.Linear(model.config.hidden_size, num_classes)\n",
                "    \n",
                "    def forward(self, input_ids, attention_mask, labels=None):\n",
                "        outputs = self.bert(input_ids=input_ids, attention_mask=attention_mask)\n",
                "        pooled_output = outputs.pooler_output\n",
                "        pooled_output = self.dropout(pooled_output)\n",
                "        logits = self.classifier(pooled_output)\n",
                "        \n",
                "        if labels is not None:\n",
                "            loss_fct = torch.nn.CrossEntropyLoss()\n",
                "            loss = loss_fct(logits.view(-1, logits.size(-1)), labels.view(-1))\n",
                "            return loss, logits\n",
                "        return logits\n",
                "\n",
                "# Create classifier\n",
                "classifier = BERTClassifier(model, len(label_encoder.classes_))\n",
                "classifier.to(device)\n",
                "\n",
                "# Count parameters\n",
                "total_params = sum(p.numel() for p in classifier.parameters())\n",
                "trainable_params = sum(p.numel() for p in classifier.parameters() if p.requires_grad)\n",
                "\n",
                "print(f\"✅ Model initialized!\")\n",
                "print(f\"📊 Total parameters: {total_params:,}\")\n",
                "print(f\"📊 Trainable parameters: {trainable_params:,}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📚 Dataset and DataLoader Setup\n",
                "Prepare data for training:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Custom dataset\n",
                "class DocumentDataset(Dataset):\n",
                "    def __init__(self, texts, labels, tokenizer, max_length):\n",
                "        self.texts = texts\n",
                "        self.labels = labels\n",
                "        self.tokenizer = tokenizer\n",
                "        self.max_length = max_length\n",
                "    \n",
                "    def __len__(self):\n",
                "        return len(self.texts)\n",
                "    \n",
                "    def __getitem__(self, idx):\n",
                "        text = str(self.texts[idx])\n",
                "        label = self.labels[idx]\n",
                "        \n",
                "        encoding = self.tokenizer(\n",
                "            text,\n",
                "            truncation=True,\n",
                "            padding='max_length',\n",
                "            max_length=self.max_length,\n",
                "            return_tensors='pt'\n",
                "        )\n",
                "        \n",
                "        return {\n",
                "            'input_ids': encoding['input_ids'].flatten(),\n",
                "            'attention_mask': encoding['attention_mask'].flatten(),\n",
                "            'labels': torch.tensor(label, dtype=torch.long)\n",
                "        }\n",
                "\n",
                "# Create datasets\n",
                "train_dataset = DocumentDataset(\n",
                "    train_df['cleaned_text'].fillna('').astype(str),\n",
                "    train_labels,\n",
                "    tokenizer,\n",
                "    CONFIG['max_length']\n",
                ")\n",
                "\n",
                "val_dataset = DocumentDataset(\n",
                "    val_df['cleaned_text'].fillna('').astype_str(),\n",
                "    val_labels,\n",
                "    tokenizer,\n",
                "    CONFIG['max_length']\n",
                ")\n",
                "\n",
                "test_dataset = DocumentDataset(\n",
                "    test_df['cleaned_text'].fillna('').astype(str),\n",
                "    test_labels,\n",
                "    tokenizer,\n",
                "    CONFIG['max_length']\n",
                ")\n",
                "\n",
                "# Create dataloaders\n",
                "train_loader = DataLoader(train_dataset, batch_size=CONFIG['batch_size'], shuffle=True)\n",
                "val_loader = DataLoader(val_dataset, batch_size=CONFIG['batch_size'], shuffle=False)\n",
                "test_loader = DataLoader(test_dataset, batch_size=CONFIG['batch_size'], shuffle=False)\n",
                "\n",
                "print(f\"✅ Datasets and DataLoaders created!\")\n",
                "print(f\"📊 Training batches: {len(train_loader)}\")\n",
                "print(f\"📊 Validation batches: {len(val_loader)}\")\n",
                "print(f\"📊 Test batches: {len(test_loader)}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🚀 Training Setup\n",
                "Prepare optimizer and scheduler:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Training setup\n",
                "print(\"🚀 Setting up training components...\")\n",
                "\n",
                "# Optimizer\n",
                "optimizer = AdamW(\n",
                "    classifier.parameters(),\n",
                "    lr=CONFIG['learning_rate'],\n",
                "    weight_decay=CONFIG['weight_decay']\n",
                ")\n",
                "\n",
                "# Learning rate scheduler\n",
                "total_steps = len(train_loader) * CONFIG['num_epochs']\n",
                "scheduler = get_linear_schedule_with_warmup(\n",
                "    optimizer,\n",
                "    num_warmup_steps=CONFIG['warmup_steps'],\n",
                "    num_training_steps=total_steps\n",
                ")\n",
                "\n",
                "# Loss function\n",
                "criterion = torch.nn.CrossEntropyLoss()\n",
                "\n",
                "print(f\"✅ Training components ready!\")\n",
                "print(f\"📊 Total training steps: {total_steps}\")\n",
                "print(f\"📊 Warmup steps: {CONFIG['warmup_steps']}\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🎯 TRAINING LOOP\n",
                "**This is where the magic happens! Run this cell to start training:**"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Training loop\n",
                "print(\"🎯 Starting BERT Training!\")\n",
                "print(f\"📚 Training for {CONFIG['num_epochs']} epochs...\")\n",
                "\n",
                "# Training history\n",
                "train_losses = []\n",
                "val_losses = []\n",
                "train_accuracies = []\n",
                "val_accuracies = []\n",
                "\n",
                "best_val_accuracy = 0\n",
                "\n",
                "for epoch in range(CONFIG['num_epochs']):\n",
                "    print(f\"\\n📚 Epoch {epoch + 1}/{CONFIG['num_epochs']}\")\n",
                "    \n",
                "    # Training\n",
                "    classifier.train()\n",
                "    total_train_loss = 0\n",
                "    correct_train = 0\n",
                "    total_train = 0\n",
                "    \n",
                "    train_progress = tqdm(train_loader, desc=f\"Training Epoch {epoch + 1}\")\n",
                "    \n",
                "    for batch in train_progress:\n",
                "        # Move to device\n",
                "        input_ids = batch['input_ids'].to(device)\n",
                "        attention_mask = batch['attention_mask'].to(device)\n",
                "        labels = batch['labels'].to(device)\n",
                "        \n",
                "        # Forward pass\n",
                "        loss, logits = classifier(input_ids, attention_mask, labels)\n",
                "        \n",
                "        # Backward pass\n",
                "        loss.backward()\n",
                "        \n",
                "        # Gradient clipping\n",
                "        torch.nn.utils.clip_grad_norm_(classifier.parameters(), CONFIG['max_grad_norm'])\n",
                "        \n",
                "        # Optimizer step\n",
                "        optimizer.step()\n",
                "        scheduler.step()\n",
                "        optimizer.zero_grad()\n",
                "        \n",
                "        # Metrics\n",
                "        total_train_loss += loss.item()\n",
                "        predictions = torch.argmax(logits, dim=1)\n",
                "        correct_train += (predictions == labels).sum().item()\n",
                "        total_train += labels.size(0)\n",
                "        \n",
                "        # Update progress bar\n",
                "        train_progress.set_postfix({\n",
                "            'Loss': f'{loss.item():.4f}',\n",
                "            'Acc': f'{100 * correct_train / total_train:.2f}%'\n",
                "        })\n",
                "    \n",
                "    # Validation\n",
                "    classifier.eval()\n",
                "    total_val_loss = 0\n",
                "    correct_val = 0\n",
                "    total_val = 0\n",
                "    \n",
                "    with torch.no_grad():\n",
                "        for batch in tqdm(val_loader, desc=f\"Validation Epoch {epoch + 1}\"):\n",
                "            input_ids = batch['input_ids'].to(device)\n",
                "            attention_mask = batch['attention_mask'].to(device)\n",
                "            labels = batch['labels'].to(device)\n",
                "            \n",
                "            loss, logits = classifier(input_ids, attention_mask, labels)\n",
                "            \n",
                "            total_val_loss += loss.item()\n",
                "            predictions = torch.argmax(logits, dim=1)\n",
                "            correct_val += (predictions == labels).sum().item()\n",
                "            total_val += labels.size(0)\n",
                "    \n",
                "    # Calculate metrics\n",
                "    avg_train_loss = total_train_loss / len(train_loader)\n",
                "    avg_val_loss = total_val_loss / len(val_loader)\n",
                "    train_accuracy = correct_train / total_train\n",
                "    val_accuracy = correct_val / total_val\n",
                "    \n",
                "    # Store history\n",
                "    train_losses.append(avg_train_loss)\n",
                "    val_losses.append(avg_val_loss)\n",
                "    train_accuracies.append(train_accuracy)\n",
                "    val_accuracies.append(val_accuracy)\n",
                "    \n",
                "    # Print results\n",
                "    print(f\"📊 Train Loss: {avg_train_loss:.4f}, Train Acc: {train_accuracy:.4f}\")\n",
                "    print(f\"📊 Val Loss: {avg_val_loss:.4f}, Val Acc: {val_accuracy:.4f}\")\n",
                "    \n",
                "    # Save best model\n",
                "    if val_accuracy > best_val_accuracy:\n",
                "        best_val_accuracy = val_accuracy\n",
                "        torch.save(classifier.state_dict(), f\"{CONFIG['output_dir']}/best_model.pt\")\n",
                "        print(f\"💾 New best model saved! Val Acc: {val_accuracy:.4f}\")\n",
                "    \n",
                "    # Create output directory if it doesn't exist\n",
                "    os.makedirs(CONFIG['output_dir'], exist_ok=True)\n",
                "\n",
                "print(\"\\n🎉 Training Complete!\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 📈 Training Visualization\n",
                "Plot training curves:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Plot training curves\n",
                "fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(15, 5))\n",
                "\n",
                "# Loss curves\n",
                "ax1.plot(train_losses, label='Train Loss', marker='o')\n",
                "ax1.plot(val_losses, label='Val Loss', marker='s')\n",
                "ax1.set_title('Training and Validation Loss')\n",
                "ax1.set_xlabel('Epoch')\n",
                "ax1.set_ylabel('Loss')\n",
                "ax1.legend()\n",
                "ax1.grid(True)\n",
                "\n",
                "# Accuracy curves\n",
                "ax2.plot(train_accuracies, label='Train Accuracy', marker='o')\n",
                "ax2.plot(val_accuracies, label='Val Accuracy', marker='s')\n",
                "ax2.set_title('Training and Validation Accuracy')\n",
                "ax2.set_xlabel('Epoch')\n",
                "ax2.set_ylabel('Accuracy')\n",
                "ax2.legend()\n",
                "ax2.grid(True)\n",
                "\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Save training curves\n",
                "plt.savefig(f\"{CONFIG['output_dir']}/training_curves.png\", dpi=300, bbox_inches='tight')\n",
                "print(f\"📈 Training curves saved to {CONFIG['output_dir']}/training_curves.png\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🧪 Final Evaluation\n",
                "Test the model on the test set:"
            ]
        },
        {
            "cell_type": "code",
            "execution_count": None,
            "metadata": {},
            "outputs": [],
            "source": [
                "# Load best model\n",
                "print(\"🧪 Loading best model for final evaluation...\")\n",
                "classifier.load_state_dict(torch.load(f\"{CONFIG['output_dir']}/best_model.pt\"))\n",
                "classifier.eval()\n",
                "\n",
                "# Test evaluation\n",
                "all_predictions = []\n",
                "all_labels = []\n",
                "total_test_loss = 0\n",
                "correct_test = 0\n",
                "total_test = 0\n",
                "\n",
                "with torch.no_grad():\n",
                "    for batch in tqdm(test_loader, desc=\"Testing\"):\n",
                "        input_ids = batch['input_ids'].to(device)\n",
                "        attention_mask = batch['attention_mask'].to(device)\n",
                "        labels = batch['labels'].to(device)\n",
                "        \n",
                "        loss, logits = classifier(input_ids, attention_mask, labels)\n",
                "        \n",
                "        total_test_loss += loss.item()\n",
                "        predictions = torch.argmax(logits, dim=1)\n",
                "        correct_test += (predictions == labels).sum().item()\n",
                "        total_test += labels.size(0)\n",
                "        \n",
                "        all_predictions.extend(predictions.cpu().numpy())\n",
                "        all_labels.extend(labels.cpu().numpy())\n",
                "\n",
                "# Calculate final metrics\n",
                "final_test_loss = total_test_loss / len(test_loader)\n",
                "final_test_accuracy = correct_test / total_test\n",
                "\n",
                "print(f\"\\n🎯 Final Test Results:\")\n",
                "print(f\"📊 Test Loss: {final_test_loss:.4f}\")\n",
                "print(f\"📊 Test Accuracy: {final_test_accuracy:.4f} ({final_test_loss*100:.2f}%)\")\n",
                "\n",
                "# Classification report\n",
                "print(f\"\\n📋 Classification Report:\")\n",
                "print(classification_report(all_labels, all_predictions, target_names=label_encoder.classes_))\n",
                "\n",
                "# Confusion matrix\n",
                "cm = confusion_matrix(all_labels, all_predictions)\n",
                "plt.figure(figsize=(10, 8))\n",
                "sns.heatmap(cm, annot=True, fmt='d', cmap='Blues', xticklabels=label_encoder.classes_, yticklabels=label_encoder.classes_)\n",
                "plt.title('Confusion Matrix')\n",
                "plt.xlabel('Predicted')\n",
                "plt.ylabel('Actual')\n",
                "plt.xticks(rotation=45)\n",
                "plt.yticks(rotation=0)\n",
                "plt.tight_layout()\n",
                "plt.show()\n",
                "\n",
                "# Save final model\n",
                "torch.save(classifier.state_dict(), f\"{CONFIG['output_dir']}/final_model.pt\")\n",
                "print(f\"💾 Final model saved to {CONFIG['output_dir']}/final_model.pt\")"
            ]
        },
        {
            "cell_type": "markdown",
            "metadata": {},
            "source": [
                "## 🎉 Training Complete!\n",
                "\n",
                "Your BERT model has been trained and evaluated! Here's what you have:\n",
                "\n",
                "### 📁 Output Files:\n",
                "- `best_model.pt` - Best model based on validation accuracy\n",
                "- `final_model.pt` - Final model after all epochs\n",
                "- `training_curves.png` - Training visualization\n",
                "\n",
                "### 🚀 Next Steps:\n",
                "1. **Use the trained model** for inference on new documents\n",
                "2. **Fine-tune hyperparameters** if needed\n",
                "3. **Deploy the model** for production use\n",
                "4. **Train ViT model** for image classification\n",
                "\n",
                "### 📊 Model Performance:\n",
                "Check the test accuracy and confusion matrix above to see how well your model performs!"
            ]
        }
    ],
    "metadata": {
        "kernelspec": {
            "display_name": "Python 3",
            "language": "python",
            "name": "python3"
        },
        "language_info": {
            "codemirror_mode": {
                "name": "ipython",
                "version": 3
            },
            "file_extension": ".py",
            "mimetype": "text/x-python",
            "name": "python",
            "nbconvert_exporter": "python",
            "pygments_lexer": "ipython3",
            "version": "3.8.5"
        }
    },
    "nbformat": 4,
    "nbformat_minor": 4
}

# Write the notebook to file
with open('BERT_Training_Notebook.ipynb', 'w') as f:
    json.dump(notebook_content, f, indent=1)

print("✅ Jupyter notebook created successfully!")
print("📁 File: BERT_Training_Notebook.ipynb")
print("🚀 You can now open it with: jupyter notebook BERT_Training_Notebook.ipynb")
